name: pycorrelate-dev
channels:
  - conda-forge
dependencies:
- python==3.5
- pandoc
- h5py
- numba
- matplotlib
- nbformat
- jupyter_client
- ipython
- ipykernel
- sphinx>=1.5.1
- sphinx_rtd_theme
- tornado
- entrypoints
- pip:
    - nbsphinx>=0.2.12
